development:
  adapter: postgresql
  encoding: unicode
  database: landing_page_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: landing_page_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: landing_page_production
  pool: 5
  username: plantingseason
  password: weema
  host: localhost
